version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/New_York"
    target-branch: "dev"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      babel:
        patterns:
          - "@babel*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss*"
      fontawesome:
        patterns:
          - "@fortawesome*"
      bugsnag:
        patterns:
          - "@bugsnag*"
      react:
        patterns:
          - "react"
          - "react-dom"
